trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  DOCKERHUB_USERNAME: $(DOCKERHUB_USERNAME)
  DOCKERHUB_TOKEN: $(DOCKERHUB_TOKEN)

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Use Node.js 18'

  - script: npm install
    displayName: 'Install dependencies'

  - script: npm run lint || true
    displayName: 'Lint check'

  - script: npm audit --audit-level=moderate || true
    displayName: ' Audit vulnerabilities'

  - script: npm update
    displayName: 'Upgrade npm packages'

  - task: DockerInstaller@0
    displayName: ' Install Docker'

  - script: |
      echo "${DOCKERHUB_TOKEN}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
    displayName: ' Docker Hub Login'

  - script: |
      docker build -t mohamedchliyah01/angular-app:latest .
      docker tag mohamedchliyah01/angular-app:latest mohamedchliyah01/angular-app:$(Build.BuildId)
      docker push mohamedchliyah01/angular-app:latest
      docker push mohamedchliyah01/angular-app:$(Build.BuildId)
    displayName: 'Build and Push Docker Image'

  - script: |
      curl -H "Content-Type: application/json" \
      -X POST \
      -d "{\"content\": \" Azure CI Success: Build #$(Build.BuildId) daz mezyan!\"}" \
      https://discord.com/api/webhooks/1374541317203300492/eBq-330IkJ1_ZJZRiidtB5LUXIoLVrUHbPweFFDACCommoQRIsdBCJytRIXyz5TeRQBp
    condition: succeeded()
    displayName: ' Discord Notification (Success)'

  - script: |
      curl -H "Content-Type: application/json" \
      -X POST \
      -d "{\"content\": \"Azure CI Failed: Build #$(Build.BuildId) ma dazch mezyan \"}" \
      https://discord.com/api/webhooks/1374541317203300492/eBq-330IkJ1_ZJZRiidtB5LUXIoLVrUHbPweFFDACCommoQRIsdBCJytRIXyz5TeRQBp
    condition: failed()
    displayName: ' Discord Notification (Failure)'
