name: CI - Build and Push Docker Image for Angular App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  angular-docker:
    runs-on: ubuntu-latest
    steps:
      - name:  Checkout code
        uses: actions/checkout@v2

      - name:  Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name:  Build and Push Angular Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            mohamedchliyah01/angular-app:latest
            mohamedchliyah01/angular-app:${{ github.run_number }}

      - name:  Show image tags
        run: |
          echo " Image published to Docker Hub:"
          echo " mohamedchliyah01/angular-app:latest"
          echo " mohamedchliyah01/angular-app:${{ github.run_number }}"
 